### ISSUE TITLE
Won't work in Android Amlogic S905 with ARM Cortex-A53

### ISSUE THREAD

**Issue by ChopChopKodi** [DiMartinoXBMC/script.module.libtorrent#5]
It seems that the architecture is aarch64 and the instruction set armeabi-v7a, armeabi if it helps

The log writes this sentences:

20:11:38 T:18446744072300349496  NOTICE: ### [python-libtorrent v.1.1.0e]: pathname = /data/data/org.xbmc.kodi/cache/apk/assets/libtorrent.so
20:11:38 T:18446744072300349496  NOTICE: ### [python-libtorrent v.1.1.0e]: Imported libtorrent v1.1.0.0 from "/data/data/org.xbmc.kodi/cache/apk/assets/"
20:11:38 T:18446744072300349496  NOTICE: ### [python-libtorrent v.1.1.0e]: Imported libtorrent v1.1.0.0 from get_libtorrent()

But when using Torrenter it won't find the library

ImportError: No module named python_libtorrent

**Comment by DiMartinoXBMC** [comment]
can you please provide full log

**Comment by ChopChopKodi** [comment]
When I removed the try: and finally: from these lines

https://github.com/DiMartinoXBMC/script.module.libtorrent/blob/cf9658cf5f6f51c1a6a73fe280acc3e897f2d74f/python_libtorrent/python_libtorrent/__init__.py#L143-L146

I've gotten the following message in the log:

19:41:36 T:18446744072306687576   ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.libtorrent-master/python_libtorrent/python_libtorrent/**init**.py:144: RuntimeWarning: to-Python converter for libtorrent::file_storage already registered; second conversion method ignored.

It seems that the try: masked the error exception and the  library is not compiled correctly though it seems only a warning.

No matter what versions I load I got the same message

**Comment by ChopChopKodi** [comment]
I don't know what I've done but now it works. Sorry
