### ISSUE TITLE
New version of libtorrent not imported until Kodi is reset

### ISSUE THREAD

**Issue by ChopChopKodi** [DiMartinoXBMC/script.module.libtorrent#6]
When I force the version of libtorrent to use, the addon unzips and installs the new library version in the temporary folder but then, when I press the run button, it always imports the old one until I close Kodi and open it again.
Don't know if it's a bug but it feels strange

**Comment by DiMartinoXBMC** [comment]
It's not a bug, kodi (or should I say python) imports library only 1 time, you kinda have to use "del" to unimport it, that slows work A LOT, so if you want to force it in your plugin, just delete the namespace.
